<?php
// Indonesian (id) placeholder translations
return [
    'commands' => [ 'menu' => 'buka menu', 'help' => 'tampilkan bantuan', 'login' => 'tautan masuk ajaib', 'balance' => 'tampilkan saldo', 'topup' => 'isi dompet', 'myproxies' => 'daftar layanan aktif', 'plans' => 'paket', 'orders' => 'pesanan', 'buy' => 'beli paket dengan id', 'config' => 'ambil konfigurasi', 'reset' => 'reset trafik', 'status' => 'status', 'support' => 'dukungan', 'signup' => 'buat akun', 'profile' => 'profil' ],
    'buttons' => [ 'menu' => 'Menu', 'plans' => 'Paket', 'orders' => 'Pesanan', 'my_services' => 'Layanan', 'wallet' => 'Dompet', 'support' => 'Dukungan', 'profile' => 'Profil', 'sign_up' => 'Daftar', 'back_to_menu' => 'Kembali', 'config' => 'Konfigurasi', 'reset' => 'Reset', 'custom_amount' => 'Nominal lain', 'download_qr' => 'Unduh QR', 'yes_reset' => 'Ya', 'cancel' => 'Batal', 'users' => 'Pengguna', 'servers' => 'Server', 'statistics' => 'Statistik', 'broadcast' => 'Siaran', 'refresh' => 'Segarkan', 'topup_wallet' => 'Isi', 'open_orders' => 'Pesanan terbuka', 'filters' => 'Filter', 'clear_filters' => 'Bersihkan', 'buy_plan' => 'Beli :name (:price)', 'topped_up_refresh' => 'Sudah isi – segarkan', 'confirm_purchase' => 'Konfirmasi', 'status' => 'Status', 'promotions' => 'Promo', 'refer_friend' => 'Ajak teman', 'coupons' => 'Kupon', 'open_dashboard' => 'Dasbor', 'edit_name' => 'Ubah nama', 'edit_email' => 'Ubah email' ],
    'common' => [ 'browse_plans' => 'Lihat paket', 'help' => 'Bantuan', 'promotions' => 'Promo', 'open_dashboard' => 'Buka dasbor', 'open' => 'Buka', 'prev' => 'Sebelum', 'next' => 'Berikut', 'all' => 'Semua', 'clear' => 'Bersih', 'actions' => 'Aksi', 'back' => 'Kembali', 'more' => 'Lainnya', 'loading' => 'Memuat...' ],
    'wallet' => [ 'title' => 'Saldo Dompet', 'balance' => 'Saldo', 'menu_hint' => 'Gunakan tombol di bawah.', 'topup_hint' => 'Butuh kredit? Isi sekarang.' ],
    'topup' => [ 'title' => 'Isi Dompet', 'current' => 'Saldo sekarang', 'methods' => 'Metode pembayaran', 'method_cards' => 'Kartu', 'method_paypal' => 'PayPal', 'method_bitcoin' => 'Bitcoin', 'method_monero' => 'Monero', 'method_solana' => 'Solana', 'instant' => 'Sebagian besar metode instan.', 'min' => 'Minimal mungkin berlaku.' ],
    'menu' => [ 'title' => 'Menu Utama', 'pick' => 'Pilih opsi.' ],
    'admin' => [ 'panel_title' => 'Panel Admin', 'open_dashboard' => 'Dasbor', 'use_config_hint' => 'Ketuk proxy untuk konfigurasi.', 'panel_pick' => 'Pilih bagian.', 'broadcast_title' => 'Siaran', 'broadcast_help' => 'Kirim pesan ke semua.', 'broadcast_usage' => 'Gunakan:', 'your_message' => 'pesan_anda', 'broadcast_example_label' => 'Contoh:', 'broadcast_example_text' => 'Hai! Fitur baru.', 'broadcast_done' => 'Selesai siaran', 'sent' => 'Terkirim', 'failed' => 'Gagal', 'total_users' => 'Total pengguna', 'user_stats_title' => 'Stat pengguna', 'system_stats_title' => 'Stat sistem', 'server_health_title' => 'Kesehatan server', 'panel' => 'Panel', 'name' => 'Nama', 'email' => 'Email', 'joined' => 'Bergabung', 'last_login' => 'Login terakhir', 'total_orders' => 'Total pesanan', 'active_proxies' => 'Proxy aktif', 'telegram' => 'Telegram', 'telegram_linked_label' => 'Tersambung', 'telegram_not_linked_label' => 'Belum', 'link_account_first' => 'Hubungkan dulu: :url', 'code_invalid' => 'Kode tidak valid', 'user_not_found_simple' => 'Pengguna tidak ditemukan', 'telegram_already_linked' => 'Sudah terhubung', 'linking_success' => 'Terhubung: :name', 'total_servers' => 'Total server', 'active' => 'Aktif', 'inactive' => 'Nonaktif', 'server_details' => 'Detail server', 'max' => 'Maks :count', 'avg_load' => 'Rata beban', 'more_servers' => '...+ :count', 'active_users' => 'Pengguna aktif', 'telegram_linked' => 'Telegram terhubung', 'new_7d' => 'Baru (7h)', 'completed' => 'Selesai', 'pending' => 'Tertunda', 'total_revenue' => 'Total pendapatan', 'today_revenue' => 'Pendapatan hari ini', 'today_orders' => 'Pesanan hari ini', 'server_stats' => 'Stat server', 'last_updated' => 'Terakhir perbarui' ],
    'plans' => [ 'title' => 'Paket tersedia', 'days' => ':days hari', 'monthly' => 'Bulanan', 'unlimited' => 'Tak terbatas', 'page' => 'Hal :page / :total' ],
    'orders' => [ 'title' => 'Pesanan Anda', 'empty' => 'Tidak ada pesanan.' ],
    'services' => [ 'title' => 'Layanan Aktif', 'status' => 'Status', 'traffic' => 'Lalu lintas', 'expires' => 'Berakhir', 'empty' => 'Tidak ada layanan.' ],
    'status' => [ 'account_title' => 'Status Akun', 'user' => 'Pengguna', 'balance' => 'Saldo', 'active' => 'Layanan aktif', 'active_label' => 'Aktif', 'inactive_label' => 'Nonaktif', 'member_since' => 'Sejak', 'dashboard' => 'Dasbor' ],
    'config' => [ 'title' => 'Konfigurasi Layanan', 'plan' => 'Paket', 'server' => 'Server', 'client_link' => 'Panel pengguna', 'subscription' => 'Tautan langganan', 'json' => 'JSON konfigurasi', 'dashboard' => 'Akses dasbor' ],
    'filters' => [ 'country' => 'Negara', 'category' => 'Kategori', 'duration' => 'Durasi' ],
    'messages' => [ 'unknown' => 'Perintah tidak dikenal /help', 'rate_limited' => 'Terlalu cepat.', 'choose_filters' => 'Pilih filter:', 'more_menu' => 'Opsi lainnya:', 'no_services' => 'Tidak ada layanan aktif', 'config_need_id' => 'Perlu id', 'config_not_found' => 'Konfigurasi tidak ditemukan', 'service_not_found' => 'Layanan tidak ditemukan', 'reset_need_id' => 'Id diperlukan untuk reset', 'client_not_found' => 'Klien tidak ada', 'client_not_found_or_reset' => 'Tidak ada / tidak bisa reset', 'need_account_profile' => 'Perlu akun', 'buy_topup_hint' => 'Saldo rendah, isi lagi', 'order_issue' => 'Masalah pesanan', 'order_completed_block' => 'Selesai: :url', 'order_ready_title' => 'Siap', 'order_id_line' => 'Id: :id', 'order_server_line' => 'Server: :server', 'order_status_line' => 'Status: :status', 'quick_actions_below' => '🔖 Aksi cepat di bawah' ],
    'help' => [ 'title' => 'Referensi Perintah', 'section_account' => 'Akun', 'start' => 'Mulai / tautkan', 'balance' => 'Tampilkan saldo', 'topup' => 'Isi dompet', 'signup' => 'Buat akun', 'profile' => 'Profil', 'section_services' => 'Layanan', 'myproxies' => 'Daftar layanan', 'config' => 'Konfigurasi layanan', 'reset' => 'Reset trafik', 'status' => 'Status layanan', 'section_plans' => 'Paket & Pesanan', 'plans' => 'Paket', 'orders' => 'Daftar pesanan', 'buy' => 'Beli (plan_id)', 'section_support' => 'Dukungan', 'support' => 'Pesan dukungan', 'help' => 'Tampilkan bantuan ini' ],
];
