version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - ./database:/var/www/html/database
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
        depends_on:
            - redis
        command: php artisan serve --host=0.0.0.0 --port=8000

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - redis
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
        command: php artisan queue:work

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - redis
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
        command: php artisan schedule:work
